'use client';

import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';

export default function AboutPage() {
  const currentYear = new Date().getFullYear();

  return (
    <div className="h-full overflow-y-auto no-scrollbar">
      <div className="container py-8 max-w-4xl mx-auto">
        <Card className="bg-card/80 backdrop-blur-sm border border-border/20">
          <CardHeader>
            <CardTitle className="font-headline text-3xl text-center">
              About PersonaForge
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-8 text-muted-foreground">
            
            <section>
              <h2 className="text-2xl font-headline text-foreground mb-4">Welcome</h2>
              <p>
                PersonaForge is an application designed to let you create, customize, and interact with unique AI-powered personas. Whether for creative writing, role-playing, or simply exploring the potential of conversational AI, PersonaForge provides a sandboxed environment for your imagination. All your data, including persona details and chat histories, is stored locally and securely in your browser's IndexedDB, ensuring your creations remain private.
              </p>
            </section>
            
            <Separator />

            <section>
              <h2 className="text-2xl font-headline text-foreground mb-4">Privacy Policy</h2>
              <p className="mb-2">
                Your privacy is paramount. PersonaForge operates almost entirely on your local device.
              </p>
              <ul className="list-disc pl-5 space-y-2">
                <li><strong>Local Data Storage:</strong> All persona data, chat messages, and user settings are stored exclusively in your web browser's IndexedDB. This data is not uploaded to, or stored on, any server controlled by us.</li>
                <li><strong>AI Interaction Data:</strong> To enable chat functionality, your conversation prompts (including persona details and chat history) are sent to the Google Gemini API. Please be aware that this data is subject to Google's own privacy policies and terms of service.</li>
                <li><strong>Sensitive Information:</strong> We strongly advise against entering any real, personal, or sensitive information (such as passwords, credit card numbers, or personal addresses) into your conversations.</li>
              </ul>
            </section>

            <Separator />

            <section>
              <h2 className="text-2xl font-headline text-foreground mb-4">Guidelines & Disclaimer</h2>
               <p className="mb-2">
                By using PersonaForge, you agree to the following terms:
              </p>
              <ul className="list-disc pl-5 space-y-2">
                <li><strong>User Responsibility:</strong> You are solely responsible for the content you create and the interactions you have with the AI personas. The AI-generated content is for entertainment purposes only and should not be considered factual or professional advice.</li>
                <li><strong>Content Guardrails:</strong> The application has built-in restrictions to prevent the generation of content related to religious figures, political debates, sexuality, or other controversial topics. These guardrails are in place to foster a safe and neutral creative environment.</li>
                <li><strong>No Liability:</strong> Musheer Alam and any associated parties are not liable for any content generated by the AI, any data loss, or any other issues arising from the use of this application. You use PersonaForge at your own risk.</li>
              </ul>
            </section>
            
            <Separator />

            <div className="text-center text-sm">
              <p>&copy; {currentYear} Musheer Alam. All Rights Reserved.</p>
            </div>

            <div className="text-center pt-4">
                <Button asChild>
                    <Link href="/">
                        <ArrowLeft className="mr-2 h-4 w-4" />
                        Back to Home
                    </Link>
                </Button>
            </div>

          </CardContent>
        </Card>
      </div>
    </div>
  );
}
