package com.simusoul.app.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AboutScreen(onNavigateBack: () -> Unit) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(16.dp)
    ) {
        Card(
            modifier = Modifier.fillMaxWidth(),
            colors = CardDefaults.cardColors(
                containerColor = MaterialTheme.colorScheme.surface.copy(alpha = 0.8f)
            )
        ) {
            Column(modifier = Modifier.padding(24.dp)) {
                Text(
                    text = "About SimuSoul",
                    style = MaterialTheme.typography.headlineMedium,
                    textAlign = TextAlign.Center,
                    modifier = Modifier.fillMaxWidth()
                )
                
                Spacer(modifier = Modifier.height(24.dp))
                
                Text(
                    text = "Welcome",
                    style = MaterialTheme.typography.titleLarge
                )
                Text(
                    text = "SimuSoul is an application designed to let you create, customize, and interact with unique AI-powered personas. Whether for creative writing, role-playing, or simply exploring the potential of conversational AI, SimuSoul provides a sandboxed environment for your imagination. All your data, including persona details and chat histories, is stored locally and securely on your device.",
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                
                Spacer(modifier = Modifier.height(16.dp))
                HorizontalDivider()
                Spacer(modifier = Modifier.height(16.dp))
                
                Text(
                    text = "Privacy Policy",
                    style = MaterialTheme.typography.titleLarge
                )
                Text(
                    text = """
Your privacy is paramount. SimuSoul operates almost entirely on your local device.

• Local Data Storage: All persona data, chat messages, and user settings are stored exclusively on your device. This data is not uploaded to any server controlled by us.

• AI Interaction Data: To enable chat functionality, your conversation prompts (including persona details and chat history) are sent to the Google Gemini API. This data is subject to Google's privacy policies.

• Sensitive Information: We strongly advise against entering any real, personal, or sensitive information into your conversations.
                    """.trimIndent(),
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                
                Spacer(modifier = Modifier.height(16.dp))
                HorizontalDivider()
                Spacer(modifier = Modifier.height(16.dp))
                
                Text(
                    text = "Guidelines & Disclaimer",
                    style = MaterialTheme.typography.titleLarge
                )
                Text(
                    text = """
By using SimuSoul, you agree to the following terms:

• User Responsibility: You are solely responsible for the content you create and the interactions you have with AI personas. AI-generated content is for entertainment purposes only.

• Content Guardrails: The application has built-in restrictions to prevent generation of inappropriate content.

• No Liability: Musheer Alam and associated parties are not liable for any content generated by the AI, any data loss, or any issues arising from the use of this application.
                    """.trimIndent(),
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                
                Spacer(modifier = Modifier.height(24.dp))
                
                Text(
                    text = "© ${java.util.Calendar.getInstance().get(java.util.Calendar.YEAR)} Musheer Alam. All Rights Reserved.",
                    style = MaterialTheme.typography.bodySmall,
                    textAlign = TextAlign.Center,
                    modifier = Modifier.fillMaxWidth()
                )
                
                Spacer(modifier = Modifier.height(16.dp))
                
                Button(
                    onClick = onNavigateBack,
                    modifier = Modifier.align(Alignment.CenterHorizontally)
                ) {
                    Icon(Icons.Default.ArrowBack, contentDescription = null)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Back to Home")
                }
            }
        }
    }
}
